name: Build container images

on:
  push:
    branches:
    - main

jobs:
  meta:
    name: Generate build matrix
    runs-on: ubuntu-latest
    outputs:
      build-matrix: ${{ steps.matrix.outputs.matrix-json }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Gather list of services
      id: matrix
      run: |
        matrix="$(./hack/build.py)"
        echo "matrix-json=${matrix}" >> $GITHUB_OUTPUT

  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    needs:
    - meta
    strategy:
      matrix:
        include: ${{ fromJSON(needs.meta.outputs.build-matrix) }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/rwx-labs/${{ matrix.tool }}
        tags: |
          type=edge
          type=semver,pattern={{version}}
          type=sha,format=long,prefix=sha-
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          packages=${{ join(matrix.packages, ' ') }}
          entrypoint=${{ matrix.entrypoint }}
        file: ${{ matrix.dist }}.Dockerfile

